apiVersion : apps/v1
kind: Deployment
metadata:
  name: default 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      labels:
        app: default 
    spec:
      containers:
        - name: default 
          image: mycontainerregistry007jag.azurecr.io/default
          ports:
          - containerPort: default